INSERT INTO `items` (`name`, `label`, `weight`, `can_remove`, `stackable`, `closeonuse`, `description`) VALUES
('mechanic_tools', 'Mechanic Tools', 5, 0, 1, 1, 'Mechanic Part'),
('toolbox', 'Tool Box', 10, 0, 1, 1, 'Mechanic Part'),
('turbo_lvl_1', 'GARET Turbo', 15, 0, 1, 1, 'Mechanic Part'),
('nos', 'Nitro', 10, 0, 1, 1, 'Mechanic Part'),
('stock_transmission', 'Stock Transmission', 50, 0, 0, 1, 'Mechanic Part'),
('race_transmission', 'Race Transmission RWD', 50, 0, 0, 1, 'Mechanic Part'),
('race_transmission_4wd', 'Race Transmission 4WD', 50, 0, 1, 1, 'Mechanic Part'),
('race_transmission_fwd', 'Race Transmission FWD', 50, 0, 1, 1, 'Mechanic Part'),
('stock_suspension', 'Race Suspension', 20, 0, 1, 1, 'Mechanic Part'),
('race_suspension', 'Race Suspension', 20, 0, 1, 1, 'Mechanic Part'),
('michelin_tires', 'Michelin Tires', 40, 0, 1, 1, 'Mechanic Part'),
('race_brakes', 'Race Breaks', 15, 0, 1, 1, 'Mechanic Part'),
('stock_oil', 'Stock Oil', 10, 0, 1, 1, 'Mechanic Part'),
('shell_oil', 'Shell Oil', 10, 0, 1, 1, 'Mechanic Part'),
('stock_engine', 'Stock Engine', 50, 0, 0, 1, 'Mechanic Part'),
('v8engine', 'V8 Engine', 50, 0, 0, 1, 'Mechanic Part'),
('2jzengine', '2JZ Engine', 50, 0, 0, 1, 'Mechanic Part'),
('lambov10', 'lambov10', 50, 0, 0, 1, 'Mechanic Part'),
('musv8', 'musv8', 50, 0, 0, 1, 'Mechanic Part'),
('shonen', 'shonen', 50, 0, 0, 1, 'Mechanic Part'),
('rb26det', 'rb26det', 50, 0, 0, 1, 'Mechanic Part'),
('rotary7', 'rotary7', 50, 0, 0, 1, 'Mechanic Part'),
('m297zonda', 'm297zonda', 50, 0, 0, 1, 'Mechanic Part'),
('m158huayra', 'm158huayra', 50, 0, 0, 1, 'Mechanic Part'),
('k20a', 'k20a', 50, 0, 0, 1, 'Mechanic Part'),
('gt3flat6', 'gt3flat6', 50, 0, 0, 1, 'Mechanic Part'),
('predatorv8', 'predatorv8', 50, 0, 0, 1, 'Mechanic Part'),
('p60b40', 'p60b40', 50, 0, 0, 1, 'Mechanic Part'),
('stock_tires', 'Stock Tires', 50, 0, 0, 1, 'Mechanic Part'),
('michelin_tires', 'Michelin Tires', 50, 0, 0, 1, 'Mechanic Part'),
('stock_brakes', 'Stock Brakes', 50, 0, 1, 1, 'Mechanic Part'),
('race_brakes', 'Race Brakes', 50, 0, 1, 1, 'Mechanic Part'),
('stock_sparkplugs', 'Stock Sparkplugs', 50, 0, 1, 1, 'Mechanic Part'),
('ngk_sparkplugs', 'NGK Sparkplugs', 50, 0, 1, 1, 'Mechanic Part');