--[[ local section = {
    pos = vector3(-78.99, -819.1035, 326.17),   
    label = '👞',
    help = 'Press ~INPUT_CONTEXT~ to open shop menu',
    components = {
        {
            label = 'Mothers Face',
            name = 'mom',
            from = 0,
            to = 44,
            current = 0,
            price = -1,
        },
        {
            label = 'Dad Face',
            name = 'dad',
            from = 0,
            to = 44,
            current = 0,
            price = -1,
        },
        {
            label = 'Resemblence',
            name = 'face_md_weight',
            from = 0,
            to = 50,
            current = 0,
            price = -1,
        },
        {
            label = 'Skin Tone',
            name = 'skin_md_weight',
            from = 0,
            to = 50,
            current = 0,
            price = -1,
        },
        {
            label = 'Hair Style',
            name = 'hair_1',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
  
        {
            label = 'Hair Color',
            name = 'hair_color_1',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Hair Highlights',
            name = 'hair_color_2',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Beard Type',
            name = 'beard_1',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Beard Size',
            name = 'beard_2',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Beard Color',
            name = 'beard_3',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Eyebrow Size',
            name = 'eyebrows_2',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Eyebrow Type',
            name = 'eyebrows_1',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Eyebrow Color',
            name = 'eyebrows_3',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'T-Shirt Type',
            name = 'tshirt_1',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'T-Shirt Varity',
            name = 'tshirt_2',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Torso',
            name = 'torso_1',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Torso Varity',
            name = 'torso_2',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Arms',
            name = 'arms',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Arm Varities',
            name = 'arms2',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Pants',
            name = 'pants_1',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Pant Varities',
            name = 'pants_2',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Shoe Types',
            name = 'shoes_1',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Shoe Varities',
            name = 'shoes_2',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Mask Types',
            name = 'mask_1',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Mask Varities',
            name = 'mask_2',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Bulletproof Vests',
            name = 'bproof_1',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Bulletproof Vest Varities',
            name = 'bproof_2',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Chain Types',
            name = 'chain_1',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Chain Varities',
            name = 'chain_2',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Helmet Type',
            name = 'helmet_1',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Helmet Varities',
            name = 'helmet_2',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Glasses Type',
            name = 'glasses_1',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Glasses Varities',
            name = 'glasses_2',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Watches Type',
            name = 'watches_1',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Watches Varities',
            name = 'watches_2',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Bag Type',
            name = 'bags_1',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Bag Color',
            name = 'bags_2',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
        {
            label = 'Eye Color',
            name = 'eye_color',
            from = 0,
            to = 500,
            current = 0,
            price = -1,
        },
    },
    cam = {
      offset = {
          x = 0.3,
          y = 2.0, -- does
          z = -0.3
      },
      pointOffset = {
          x = 0,
          y = -13.0,
          z = 0.4
      },
      taskHeading = 309.66
  },
  size = 1.2, --Default 1
  renderDistance = 10.0,
  }

RegisterCommand("fixme", function()
    TriggerEvent("rcore_clothes:openMenu", section, 1, 1)
  end)  ]] 